<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>symrm</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RootNamespace>BehaviourStudio.Tools</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Ba2.cs" />
    <Compile Include="Tests.cs" />
    <Compile Include="../../src/Hkx/*.cs" />
    <Compile Include="../../src/Nif/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../src/Hkx/HavokClassLayouts.json" />
    <EmbeddedResource Include="../../src/Hkx/HavokEnumNames.json" Condition="Exists('../../src/Hkx/HavokEnumNames.json')" />
    <EmbeddedResource Include="../../src/Hkx/HavokClassTypes.json" Condition="Exists('../../src/Hkx/HavokClassTypes.json')" />
  </ItemGroup>
</Project>
